name: Create and publish a package
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.TEST_TKS_CI_USERNAME }}
        password: ${{ secrets.TEST_TKS_CI_TOKEN }}
    
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          sktcloud/tks-info:${{ github.head_ref }}-${{ github.sha::8 }}, 
          sktcloud/tks-info:latest
        build-args: |
          PRV_GITHUB_TOKEN=${{ secrets.PRV_GITHUB_TOKEN }}
