name: Create and publish a package
on:
  pull_request:
    branches:
      - main
      - 'release**'
jobs:
  build-and-pPush-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: |
          sktcloud/tks-info:${{ github.head_ref }}-${{ github.sha }}
        build-args: |
          PRV_GITHUB_TOKEN=${{ secrets.PRV_GITHUB_TOKEN }}
